# configs/model_params.yaml
data:
  time_steps: 60
  num_features: 12
  max_seq_length: 128
  batch_size: 32

model:
  lstm_units_1: 128
  lstm_units_2: 64
  dense_units_1: 128
  dense_units_2: 64
  dropout_rate: 0.5
  learning_rate: 0.001

training:
  epochs: 1
  validation_split: 0.2