# universes.py
UNIVERSES_METADATA = {
    "us": {
        "AAPL": {
            "name": "Apple Inc.",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "MSFT": {
            "name": "Microsoft Corp.",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "NVDA": {
            "name": "NVIDIA",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "GOOGL": {
            "name": "Alphabet Inc.",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "AMZN": {
            "name": "Amazon.com Inc.",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "META": {
            "name": "Meta Platforms",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "TSLA": {
            "name": "Tesla Inc.",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "JPM": {
            "name": "JPMorgan Chase",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "JNJ": {
            "name": "Johnson & Johnson",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "XOM": {
            "name": "Exxon Mobil",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "AMD": {
            "name": "AMD",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "NFLX": {
            "name": "Netflix",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "COST": {
            "name": "Costco",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "AVGO": {
            "name": "Broadcom",
            "exchange": "NASDAQ",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "CRM": {
            "name": "Salesforce",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "BAC": {
            "name": "Bank of America",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "WMT": {
            "name": "Walmart",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "DIS": {
            "name": "Disney",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "V": {
            "name": "Visa",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "MA": {
            "name": "Mastercard",
            "exchange": "NYSE",
            "currency": "USD",
            "timezone": "America/New_York",
        },
    },
    "india": {
        "RELIANCE.NS": {
            "name": "Reliance Industries",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "TCS.NS": {
            "name": "TCS",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "INFY.NS": {
            "name": "Infosys",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "HDFCBANK.NS": {
            "name": "HDFC Bank",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "ICICIBANK.NS": {
            "name": "ICICI Bank",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "SBIN.NS": {
            "name": "SBI",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "BHARTIARTL.NS": {
            "name": "Bharti Airtel",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "ITC.NS": {
            "name": "ITC",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "LT.NS": {
            "name": "L&T",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "HINDUNILVR.NS": {
            "name": "Hindustan Unilever",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "AXISBANK.NS": {
            "name": "Axis Bank",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "KOTAKBANK.NS": {
            "name": "Kotak Bank",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "BAJFINANCE.NS": {
            "name": "Bajaj Finance",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "MARUTI.NS": {
            "name": "Maruti Suzuki",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "ASIANPAINT.NS": {
            "name": "Asian Paints",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "SUNPHARMA.NS": {
            "name": "Sun Pharma",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "TITAN.NS": {
            "name": "Titan",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "ULTRACEMCO.NS": {
            "name": "UltraTech Cement",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "ADANIENT.NS": {
            "name": "Adani Enterprises",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
        "POWERGRID.NS": {
            "name": "Power Grid",
            "exchange": "NSE",
            "currency": "INR",
            "timezone": "Asia/Kolkata",
        },
    },
    "crypto": {
        "BTC-USD": {
            "name": "Bitcoin",
            "exchange": "CCC",
            "currency": "USD",
            "timezone": "UTC",
        },
        "ETH-USD": {
            "name": "Ethereum",
            "exchange": "CCC",
            "currency": "USD",
            "timezone": "UTC",
        },
        "SOL-USD": {
            "name": "Solana",
            "exchange": "CCC",
            "currency": "USD",
            "timezone": "UTC",
        },
    },
    "forex": {
        "EURUSD=X": {
            "name": "EUR/USD",
            "exchange": "CCY",
            "currency": "USD",
            "timezone": "UTC",
        },
        "GBPUSD=X": {
            "name": "GBP/USD",
            "exchange": "CCY",
            "currency": "USD",
            "timezone": "UTC",
        },
        "JPY=X": {
            "name": "USD/JPY",
            "exchange": "CCY",
            "currency": "JPY",
            "timezone": "UTC",
        },
    },
    "commodities": {
        "GC=F": {
            "name": "Gold",
            "exchange": "CMX",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "CL=F": {
            "name": "Crude Oil",
            "exchange": "NYM",
            "currency": "USD",
            "timezone": "America/New_York",
        },
        "SI=F": {
            "name": "Silver",
            "exchange": "CMX",
            "currency": "USD",
            "timezone": "America/New_York",
        },
    },
}
